/* USERS */
export const FETCH_USERS = 'FETCH_USERS'
export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS'
export const USER_ERRORS = 'USER_ERRORS'

export const FETCH_NOTI = 'FETCH_NOTI'
export const CREATE_NOTI = 'CREATE_NOTI'
export const CREATE_NOTI_SUCCESS = 'CREATE_NOTI_SUCCESS'
export const UPDATE_NOTI_SUCCESS = 'UPDATE_NOTI_SUCCESS'
export const GET_NOTI_DETAIL_SUCCESS = 'GET_NOTI_DETAIL_SUCCESS'
export const NOTI_ERRORS = 'NOTI_ERRORS'
export const FETCH_GROUPS_NOTI = 'FETCH_GROUPS_NOTI'
/* GROUPS USER*/
export const FETCH_GROUPS_USER = 'FETCH_GROUPS_USER'
export const FETCH_ROLE_ACTION = 'FETCH_ROLE_ACTION'
export const FETCH_DETAIL_PERMISSION = 'FETCH_DETAIL_PERMISSION'
export const FETCH_DETAIL_PERMISSION_IS_LOGIN = 'FETCH_DETAIL_PERMISSION_IS_LOGIN'
export const SUBMIT_ROLE_PERMISSION = 'SUBMIT_ROLE_PERMISSION'

/* POSTS */
export const FETCH_POSTS = 'FETCH_POSTS'
export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'
/* CATEGORIES */
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'

/* SETTINGS */
export const FETCH_ADDRESS_OFFICES = 'FETCH_ADDRESS_OFFICES'
export const CREATE_ADDRESS_OFFICE = 'CREATE_ADDRESS_OFFICE'
export const DETAIL_ADDRESS_OFFICE = 'DETAIL_ADDRESS_OFFICE'
export const DELETE_ADDRESS_OFFICE = 'DELETE_ADDRESS_OFFICE'
export const UPDATE_ADDRESS_OFFICE = 'UPDATE_ADDRESS_OFFICE'
export const UPLOAD_FILE_IMAGE_BACKGROUND_OFFICE_SUCCESS = 'UPLOAD_FILE_IMAGE_BACKGROUND_OFFICE_SUCCESS'
export const LIST_OFFICES_EXITED = 'LIST_OFFICES_EXITED'
export const CHECK_OFFICES_EXITED_SUCCESS = 'CHECK_OFFICES_EXITED_SUCCESS'
export const SEND_IMPORT_OFFICES_SUCCESS = 'SEND_IMPORT_OFFICES_SUCCESS'

export const SAVE_SETTING_OTP_REQUEST_SUCCESS = 'SAVE_SETTING_OTP_REQUEST_SUCCESS'
export const GET_SETTING_OTP_REQUEST_SUCCESS = 'GET_SETTING_OTP_REQUEST_SUCCESS'

export const SAVE_SETTING_GENERAL_REQUEST_SUCCESS = 'SAVE_SETTING_GENERAL_REQUEST_SUCCESS'
export const GET_SETTING_GENERAL_REQUEST_SUCCESS = 'GET_SETTING_GENERAL_REQUEST_SUCCESS'

export const SAVE_SETTING_TOKEN_TIMEOUT_SUCCESS = 'SAVE_SETTING_TOKEN_TIMEOUT_SUCCESS'
export const DELETE_SETTING_TOKEN_TIMEOUT_SUCCESS = 'DELETE_SETTING_TOKEN_TIMEOUT_SUCCESS'
export const GET_SETTING_TOKEN_TIMEOUT_SUCCESS = 'GET_SETTING_TOKEN_TIMEOUT_SUCCESS'
export const GET_CONDITIONAL_USE_APP = 'GET_CONDITIONAL_USE_APP'
export const SAVE_CONDITIONAL_USE_APP = 'SAVE_CONDITIONAL_USE_APP'
export const GET_MESSAGE_SOUND_STATUS = 'GET_MESSAGE_SOUND_STATUS'
export const UPDATE_MESSAGE_SOUND_STATUS_SUCCESS = 'UPDATE_MESSAGE_SOUND_STATUS_SUCCESS'
export const UPDATE_CARD_REMIND_SUCCESS = 'UPDATE_CARD_REMIND_SUCCESS'
export const UPDATE_CARD_THE_FIRST_SUCCESS = 'UPDATE_CARD_THE_FIRST_SUCCESS'
export const UPDATE_TIME_PAYMENT_OR_SETTLEMENT_SUCCESS = 'UPDATE_TIME_PAYMENT_SUCCESS'
export const UPDATE_SETTING_FOR_EKYC_SUCCESS = 'UPDATE_SETTING_FOR_EKYC_SUCCESS'

// contact setting
export const GET_CONTACT_INFO = 'GET_CONTACT_INFO'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'
export const DETAIL_CONTACT_INFO = 'DETAIL_CONTACT_INFO'

export const GET_LIST_PROVINCES = 'GET_LIST_PROVINCES'
export const GET_DETAIL_PROVINCES = 'GET_DETAIL_PROVINCES'
export const GET_PROVINCES = 'GET_PROVINCES'

export const GET_TUTORIALS_SUCCESS = 'GET_TUTORIALS_SUCCESS'
export const ADD_TUTORIALS_SUCCESS = 'ADD_TUTORIALS_SUCCESS'
export const DELETE_TUTORIALS_SUCCESS = 'DELETE_TUTORIALS_SUCCESS'
export const GET_TUTORIAL_SUCCESS = 'GET_TUTORIAL_SUCCESS'

export const SAVE_SETTING_RESEND_SUCCESS = 'SAVE_SETTING_RESEND_SUCCESS'
export const GET_SETTING_RESEND_DATA = 'GET_SETTING_RESEND_DATA'

/* CUSTOMER*/
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const FETCH_DEVICE_CUSTOMER = 'FETCH_DEVICE_CUSTOMER'
export const FETCH_INFO_NOTI_CUSTOMER = 'FETCH_INFO_NOTI_CUSTOMER'
export const FETCH_INFO_CUSTOMER = 'FETCH_INFO_CUSTOMER'

export const REMOVE_DEVICE_CUSTOMER_SUCCESS = 'REMOVE_DEVICE_CUSTOMER_SUCCESS'
export const RESET_PIN_CUSTOMER_SUCCESS = 'RESET_PIN_CUSTOMER_SUCCESS'
export const RESET_PASSWORD_CUSTOMER_SUCCESS = 'RESET_PASSWORD_CUSTOMER_SUCCESS'
export const UN_LOCK_OTP_CUSTOMER_SUCCESS = 'UN_LOCK_OTP_CUSTOMER_SUCCESS'
/* REQUEST CUSTOMER*/
export const FETCH_REQUESTS_CUSTOMER = 'FETCH_REQUESTS_CUSTOMER'

//* Notifications*/
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
export const PUSH_NOTIFICATION_SUCCESS = 'PUSH_NOTIFICATION_SUCCESS'
export const FETCH_LIST_GROUP_CUSTOMER_NOTIFICATIONS = 'FETCH_LIST_GROUP_CUSTOMER_NOTIFICATIONS'
export const SAVE_GROUP_CUSTOMER_NOTIFICATIONS = 'SAVE_GROUP_CUSTOMER_NOTIFICATIONS'
export const DETAIL_GROUP_CUSTOMER_NOTIFICATIONS = 'DETAIL_GROUP_CUSTOMER_NOTIFICATIONS'
export const ADD_CUSTOMER_TO_GROUP_CUSTOMER_NOTIFICATIONS_STATUS = 'ADD_CUSTOMER_TO_GROUP_CUSTOMER_NOTIFICATIONS_STATUS'
export const SAVE_CUSTOMER_NOTIFICATIONS = 'SAVE_CUSTOMER_NOTIFICATIONS'
export const DETAIL_CUSTOMER_NOTIFICATIONS = 'DETAIL_CUSTOMER_NOTIFICATIONS'

/* PUSH NOTIFICATION*/

/* NOTIFICATION FLOW */

export const FETCH_NOTIFICATION_FLOW = 'FETCH_NOTIFICATION_FLOW'
export const DETAILS_NOTIFICATION_FLOW = 'DETAILS_NOTIFICATION_FLOW'

/* FAQ*/
export const FETCH_FAQ_LIST = 'FETCH_FAQ_LIST'
export const ADD_FAQ_SUCESS = 'ADD_FAQ_SUCCESS'
export const GET_DETAIL_FAQ = 'GET_DETAIL_FAQ'
export const UPDATE_FAQ_SUCESS = 'UPDATE_FAQ_SUCESS'
export const DELETE_FAQ_SUCESS = 'DELETE_FAQ_SUCESS'
export const UPDATE_FAQ_TOPIC_SUCCESS = 'UPDATE_FAQ_TOPIC_SUCCESS'
export const SAVE_FAQ_TOPIC_SUCCESS = 'SAVE_FAQ_TOPIC_SUCCESS'

export const SAVE_FAQ_CATEGORY_SUCCESS = 'SAVE_FAQ_CATEGORY_SUCCESS'
export const UPDATE_FAQ_CATEGORY_SUCCESS = 'UPDATE_FAQ_CATEGORY_SUCCESS'
export const DELETE_FAQ_CATEGORY_SUCCESS = 'DELETE_FAQ_CATEGORY_SUCCESS'
export const GET_DETAIL_FAQ_CATEGORY = 'GET_DETAIL_FAQ_CATEGORY'

export const FETCH_LIST_FAQ_CATEGORY = 'FETCH_LIST_FAQ_CATEGORY'
export const FETCH_LIST_FAQ_CATEGORY_TOPIC = 'FETCH_LIST_FAQ_CATEGORY_TOPIC'
export const SAVE_FAQ_CATEGORY_TOPIC_SUCCESS = 'SAVE_FAQ_CATEGORY_TOPIC_SUCCESS'
export const UPDATE_FAQ_CATEGORY_TOPIC_SUCCESS = 'UPDATE_FAQ_CATEGORY_TOPIC_SUCCESS'
export const GET_DETAIL_FAQ_CATEGORY_TOPIC = 'GET_DETAIL_FAQ_CATEGORY_TOPIC'

export const SEARCH_FAQ_DATA = 'SEARCH_FAQ_DATA'
export const FAQ_KEYWORD_COMMON_LIST = 'FAQ_KEYWORD_COMMON_LIST'
export const UPDATE_FAQ_KEYWORD_COMMON_LIST = 'UPDATE_FAQ_KEYWORD_COMMON_LIST'

/* Kind Office */
export const GET_LIST_KIND_OFFICE = 'GET_LIST_KIND_OFFICE'
export const GET_DETAIL_KIND_OFFICE = 'GET_DETAIL_KIND_OFFICE'
export const ADD_KIND_OFFICE_SUCCESS = 'ADD_KIND_OFFICE_SUCCESS'
export const DELETE_KIND_OFFICE_SUCCESS = 'DELETE_KIND_OFFICE_SUCCESS'

/* Background*/
export const GET_LIST_BACKGROUND_SUCCESS = 'GET_LIST_BACKGROUND_SUCCESS'
export const SAVE_BACKGROUND_SUCCESS = 'SAVE_BACKGROUND_SUCCESS'
export const DELETE_BACKGROUND_SUCCESS = 'DELETE_BACKGROUND_SUCCESS'
export const GET_DETAIL_BACKGROUND = 'GET_DETAIL_BACKGROUND'
export const SAVE_BACKGROUND_GPS_SUCCESS = 'SAVE_BACKGROUND_GPS_SUCCESS'
export const GET_DETAIL_BACKGROUND_GPS = 'GET_DETAIL_BACKGROUND_GPS'

/* Contact Category*/
export const GET_CONTACT_CATEGORY = 'GET_CONTACT_CATEGORY'
export const ADD_CONTACT_CATEGORY_SUCCESS = 'ADD_CONTACT_CATEGORY_SUCCESS'
export const DETAIL_CONTACT_CATEGORY = 'DETAIL_CONTACT_CATEGORY'

/* Contact customer*/
export const FETCH_LIST_CONTACT_CUSTOMER_SUCCESS = 'FETCH_LIST_CONTACT_CUSTOMER_SUCCESS'
export const UPDATE_CONTACT_CUSTOMER_STATUS = 'UPDATE_CONTACT_CUSTOMER_STATUS'
export const DETAIL_CONTACT_CUSTOMER_INFO = 'DETAIL_CONTACT_CUSTOMER_INFO'

/* Customer Support*/
export const FETCH_REQUEST_MANAGEMENT_LIST = 'FETCH_REQUEST_MANAGEMENT_LIST'
export const UPDATE_REQUEST_MANAGEMENT_STATUS = 'UPDATE_REQUEST_MANAGEMENT_STATUS'
export const FETCH_REQUEST_MANAGEMENT_DETAIL = 'FETCH_REQUEST_MANAGEMENT_DETAIL'
export const FETCH_LINK_EXPORT_REQUEST_MANAGEMENT_DETAIL = 'FETCH_LINK_EXPORT_REQUEST_MANAGEMENT_DETAIL'
export const NO_DATA_EXPORT_REQUEST_MANAGEMENT = 'NO_DATA_EXPORT_REQUEST_MANAGEMENT'

/* Payment Method*/
export const GET_PAYMENT_METHOD_SUCCESS = 'GET_PAYMENT_METHOD_SUCCESS'
export const SAVE_PAYMENT_MEDTHOD_SUCCESS = 'SAVE_PAYMENT_MEDTHOD_SUCCESS'
export const GET_PAYMENT_MEDTHOD_DETAIL = 'GET_PAYMENT_MEDTHOD_DETAIL'
export const SAVE_PAYMENT_MEDTHOD_EXTERNAL_SUCCESS = 'SAVE_PAYMENT_MEDTHOD_EXTERNAL_SUCCESS'
export const SAVE_PAYMENT_MEDTHOD_INTERNAL_SUCCESS = 'SAVE_PAYMENT_MEDTHOD_INTERNAL_SUCCESS'
export const DETAIL_PAYMENT_MEDTHOD_INTERNAL = 'DETAIL_PAYMENT_MEDTHOD_INTERNAL'
export const DETAIL_PAYMENT_MEDTHOD_EXTERNAL = 'DETAIL_PAYMENT_MEDTHOD_EXTERNAL'
export const DETAIL_PAYMENT_MEDTHOD_WALLET = 'DETAIL_PAYMENT_MEDTHOD_WALLET'
export const SAVE_PAYMENT_MEDTHOD_WALLET_SUCCESS = 'SAVE_PAYMENT_MEDTHOD_WALLET_SUCCESS'

/* Loan Request*/
export const FETCH_LOAN_REQUEST_ADDITIONAL = 'FETCH_LOAN_REQUEST_ADDITIONAL'
export const FETCH_LOAN_REQUEST_INTEREST_RATE = 'FETCH_LOAN_REQUEST_INTEREST_RATE'
export const FETCH_FORCE_CLOSE_REQUEST = 'FETCH_FORCE_CLOSE_REQUEST'
export const FETCH_LINK_EXPORT_FORCE_CLOSE_DETAIL = 'FETCH_LINK_EXPORT_FORCE_CLOSE_DETAIL'
export const FETCH_LINK_EXPORT_LOAN_ADDITIONAL_DETAIL = 'FETCH_LINK_EXPORT_LOAN_ADDITIONAL_DETAIL'
export const FETCH_TENURE_DATA = 'FETCH_TENURE_DATA'
export const CREATE_TENURE_DATA = 'CREATE_TENURE_DATA'
export const CREATE_RATE_PER_YEAR_DATA = 'CREATE_RATE_PER_YEAR_DATA'
export const LOAN_LIMIT_DETAIL = 'LOAN_LIMIT_DETAIL'
export const SAVE_LOAN_LIMIT_DETAIL = 'SAVE_LOAN_LIMIT_DETAIL'
export const LOAN_INCOME_MONTH_DETAIL = 'LOAN_INCOME_MONTH_DETAIL'
export const SAVE_LOAN_INCOME_MONTH_DETAIL = 'SAVE_LOAN_INCOME_MONTH_DETAIL'
export const UPDATE_LOAN_TOPUP_STATUS = 'UPDATE_LOAN_TOPUP_STATUS'
export const UPDATE_LOAN_REQUEST_ADDITIONAL_STATUS = 'UPDATE_LOAN_REQUEST_ADDITIONAL_STATUS'
export const NO_DATA_EXPORT_FORCE_CLOSE = 'NO_DATA_EXPORT_FORCE_CLOSE'
export const NO_DATA_EXPORT_ADDITIONAL_LOAN = 'NO_DATA_EXPORT_ADDITIONAL_LOAN'

/* Background login setting */
export const GET_LIST_BACKGROUND_LOGIN_SUCCESS = 'GET_LIST_BACKGROUND_LOGIN_SUCCESS'
export const UPDATE_BACKGROUND_LOGIN_SUCCESS = 'UPDATE_BACKGROUND_LOGIN_SUCCESS'
/* Loan Guide*/
export const FETCH_LIST_LOAN_GUIDE = 'FETCH_LIST_LOAN_GUIDE'
export const SAVE_LOAN_GUIDE_SUCCESS = 'SAVE_LOAN_GUIDE_SUCCESS'

export const FETCH_LOAN_REQUEST_TOPUP = 'FETCH_LOAN_REQUEST_TOPUP'
export const FETCH_LINK_EXPORT_LOAN_TOPUP = 'FETCH_LINK_EXPORT_LOAN_TOPUP'
export const NO_DATA_EXPORT_TOPUP = 'NO_DATA_EXPORT_TOPUP'
export const FETCH_LOAN_TOPUP_SETTING = 'FETCH_LOAN_TOPUP_SETTING'
export const UPDATE_LOAN_TOPUP_SETTING = 'UPDATE_LOAN_TOPUP_SETTING'

export const GET_LOAN_GUIDE_DETAIL = 'GET_LOAN_GUIDE_DETAIL'

/* Topup customers */
export const FETCH_CUSTOMER_TOPUP = 'FETCH_CUSTOMER_TOPUP'
export const FETCH_CUSTOMER_SEARCH = 'FETCH_CUSTOMER_SEARCH'
export const CREATE_CUSTOMER_TOPUP = 'CREATE_CUSTOMER_TOPUP'
export const DETAIL_CUSTOMER_TOPUP = 'DETAIL_CUSTOMER_TOPUP'
export const IMPORT_CUSTOMER_TOPUP_SUCCESS = 'IMPORT_CUSTOMER_TOPUP_SUCCESS'

/* Upload File*/
export const UPLOAD_FILE_SUCCESS = 'UPLOAF_FILE_SUCCESS'
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR'
export const LINK_UPLOAD_FILE_SUCCESS = 'LINK_UPLOAD_FILE_SUCCESS'

/* Loan Product */
export const GET_LOAN_PRODUCTS = 'GET_LOAN_PRODUCTS'
export const LOAN_PRODUCT_PAGINATION = 'LOAN_PRODUCT_PAGINATION'

/* Unit Loan Product Campaign */
export const GET_PRODUCT_CAMPAIGNS = 'GET_PRODUCT_CAMPAIGNS'

/* Product Document */
export const PRODUCT_DOCUMENT_LIST = 'PRODUCT_DOCUMENT_LIST'
export const PRODUCT_DOCUMENT_DETAILS = 'PRODUCT_DOCUMENT_DETAILS'
export const PRODUCT_DOCUMENT_UPDATE_SUCCESS = 'PRODUCT_DOCUMENT_UPDATE_SUCCESS'
export const GET_LOAN_PRODUCTS_PARENT_MODE = 'GET_LOAN_PRODUCTS_PARENT_MODE'
export const GET_LOAN_PRODUCT_DETAIL = 'GET_LOAN_PRODUCT_DETAIL'
export const UPDATE_LOAN_PRODUCT_SUCCESS = 'UPDATE_LOAN_PRODUCT_SUCCESS'
export const GET_LOAN_PRODUCT_PARENTS_GROUP = 'GET_LOAN_PRODUCT_PARENTS_GROUP'
export const GET_PRODUCT_FROM_CORE = 'GET_PRODUCT_FROM_CORE'
export const GET_CHILD_PRODUCTS = 'GET_CHILD_PRODUCTS'
export const GET_PRODUCT_TYPE = 'GET_PRODUCT_TYPE'
export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY'
export const GET_PRIORITY_FLAG = 'GET_PRIORITY_FLAG'

/* Question */
export const GET_QUESTIONS = 'GET_QUESTIONS'
export const GET_QUESTION_DETAIL = 'GET_QUESTION_DETAIL'
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'

/* Loan Product Tenures */
export const GET_LOAN_PRODUCT_TENURES = 'GET_LOAN_PRODUCT_TENURES'
export const GET_TENOR_DETAILS = 'GET_TENOR_DETAILS'

/* Loan Product Purposes */
export const GET_LOAN_PRODUCT_PURPOSES = 'GET_LOAN_PRODUCT_PURPOSES'
export const GET_PURPOSE_DETAILS = 'GET_PURPOSE_DETAILS'
export const GET_PURPOSE_CODE_LIST = 'GET_PURPOSE_CODE_LIST'

/** Loan Application */
export const GET_LOAN_APPLICATIONS = 'GET_LOAN_APPLICATIONS'
export const UPDATE_LOAN_APPLICATION_SUCCESS = 'UPDATE_LOAN_APPLICATION_SUCCESS'
export const GET_HISTORIES_BY_LOAN_APP = 'GET_HISTORIES_BY_LOAN_APP'
export const GET_LOAN_APP_PRODUCT_TYPES = 'GET_LOAN_APP_PRODUCT_TYPES'
export const GET_LOAN_APPROVAL = 'GET_LOAN_APPROVAL'
export const GET_LOAN_APPLICATIONS_DETAILS = 'GET_LOAN_APPLICATIONS_DETAILS'
export const GET_ADDITIONAL_QUESTIONS_FOR_APPROVAL = 'GET_ADDITIONAL_QUESTIONS_FOR_APPROVAL'
export const UPDATE_DOCUMENT_SENT_CORE_SUCCESS = 'UPDATE_DOCUMENT_SENT_CORE_SUCCESS'
export const GET_LOAN_APPLICATIONS_BRE_RULES = 'GET_LOAN_APPLICATIONS_BRE_RULES'
export const NEW_CIF_SUCCESS = 'NEW_CIF_SUCCESS'
export const LINK_CIF_SUCCESS = 'LINK_CIF_SUCCESS'

/** Additional Reason */
export const GET_ALL_DOCUMENT_TYPE = 'GET_ALL_DOCUMENT_TYPE'
export const GET_DOCUMENT_TYPE_NAME = 'GET_DOCUMENT_TYPE_NAME'
export const GET_ALL_DETAIL_DOCUMENT_TYPE = 'GET_ALL_DETAIL_DOCUMENT_TYPE'
export const GET_DETAIL_DOCUMENT_TYPE = 'GET_DETAIL_DOCUMENT_TYPE'
export const UPDATE_DETAIL_DOCUMENT_TYPE_SUCCESS = 'UPDATE_DETAIL_DOCUMENT_TYPE_SUCCESS'
export const DOCUMENT_TYPE_PAGINATION = 'DOCUMENT_TYPE_PAGINATION'

/** Rejection reason */
export const GET_ALL_REJECTION_REASON = 'GET_ALL_REJECTION_REASON'
export const GET_REJECTION_REASON = 'GET_REJECTION_REASON'
export const UPDATE_REJECTION_REASON_SUCCESS = 'UPDATE_REJECTION_REASON_SUCCESS'

//* Notifications*/
export const GET_ALL_LINK_TYPE = 'GET_ALL_LINK_TYPE'
export const GET_LIST_LINK = 'GET_LIST_LINK'

/** Promotion */
export const GET_PROMOTIONS = 'GET_PROMOTIONS'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PROMOTION_DETAIL = 'GET_PROMOTION_DETAIL'
export const CREATE_PROMOTION_SUCCESS = 'CREATE_PROMOTION_SUCCESS'
export const UPDATE_PROMOTION_SUCCESS = 'UPDATE_PROMOTION_SUCCESS'

/** Promotion */
export const GET_CUSTOMER_LOGS = 'GET_GET_CUSTOMER_LOGS'
export const GET_CUSTOMER_LOG_DETAIL = 'GET_CUSTOMER_LOG_DETAIL'

/** Background Welcome */
export const GET_BACKGROUND_WELCOME = 'GET_BACKGROUND_WELCOME'
export const UPDATE_BACKGROUND_WELCOME_SUCCESS = 'UPDATE_BACKGROUND_WELCOME_SUCCESS'

/** Unit Loan Video Call Verify */
export const SET_TOKEN = 'SET_TOKEN'
export const SET_STRINGEE_STATE = 'SET_STRINGEE_STATE'
export const SET_STRINGEE_ACTION = 'SET_STRINGEE_ACTION'

export const SET_ENUM_INDEX_SELECTED = 'SET_ENUM_INDEX_SELECTED'
export const SET_ENUM_INDEX_SELECTED_CO = 'SET_ENUM_INDEX_SELECTED_CO'
export const SET_IMAGE_RESULT = 'SET_IMAGE_RESULT'
export const SET_IMAGE_RESULT_CO = 'SET_IMAGE_RESULT_CO'
export const SET_CALL_ID = 'SET_CALL_ID'
export const SET_DEVICE_TOKEN = 'SET_DEVICE_TOKEN'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_FILE_ID_SIGNATURE = 'SET_FILE_ID_SIGNATURE'
export const SET_OTP_STATUS = 'SET_OTP_STATUS'
export const SET_OTP_STATUS_CO = 'SET_OTP_STATUS_CO'
export const SET_IMAGE_RESULT_SIGNATURE = 'SET_IMAGE_RESULT_SIGNATURE'
export const SET_IMAGE_RESULT_SIGNATURE_CO = 'SET_IMAGE_RESULT_SIGNATURE_CO'
export const SET_ARN = 'SET_ARN'

export const SET_INDEX_ITEM_COLLAPSE = 'SET_INDEX_ITEM_COLLAPSE'

export const RESET_STRINGEE_ACTION = 'RESET_STRINGEE_ACTION'

export const STRINGEE_CONNECT_AUTH = 'STRINGEE_CONNECT_AUTH'
export const STRINGEE_DISCONNECT = 'STRINGEE_DISCONNECT'
export const STRINGEE_CALLING = 'STRINGEE_CALLING'
export const STRINGEE_CALLAGAIN = 'STRINGEE_CALLAGAIN'
export const SET_CURRENT_CALL = 'SET_CURRENT_CALL'
export const STRINGEE_ANSWERED = 'STRINGEE_ANSWERED'
export const STRINGEE_CONNECTED = 'STRINGEE_CONNECTED'
export const STRINGEE_MUTE = 'STRINGEE_MUTE'
export const STRINGEE_ONMIC = 'STRINGEE_ONMIC'

export const STRINGEE_CAPTURE = 'STRINGEE_CAPTURE'
export const STRINGEE_BUSY = 'STRINGEE_BUSY'
export const STRINGEE_HANGUP = 'STRINGEE_HANGUP'

export const FIREBASE_INIT = 'FIREBASE_INIT'

export const SAVED_CUSTOMER_INFO = 'SAVED_CUSTOMER_INFO'
export const SAVED_CO_INFO = 'SAVED_CO_INFO'

/* Loan Request*/
export const FETCH_LIST_RO_QUEUE = 'FETCH_LIST_RO_QUEUE'
export const RO_QUEUE_DETAIL = 'RO_QUEUE_DETAIL'
export const GET_DOCTYPE_BY_KIND = 'GET_DOCTYPE_BY_KIND'
export const SEND_PAYMENT_SCHEDULE = 'SEND_PAYMENT_SCHEDULE'
export const GET_IMAGES_TYPE_DETAIL = 'GET_IMAGES_TYPE_DETAIL'
export const GET_LIST_DOCUMENT_FROM_PORTAL = 'GET_LIST_DOCUMENT_FROM_PORTAL'
export const SET_ITEM_RO_QUEUE = 'SET_ITEM_RO_QUEUE'
export const WAITING_VERIFICATION = 'WAITING_VERIFICATION'
export const AGREE_SIGN = 'AGREE_SIGN'
export const AGREE_SIGN_CO = 'AGREE_SIGN_CO'
export const SET_SIGN_STATUS = 'SET_SIGN_STATUS'
export const SET_IS_SIGNED = 'SET_IS_SIGNED'
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS'
export const VALIDATE_MAKE_STATUS = 'VALIDATE_MAKE_STATUS'
export const CALL_ENDED = 'CALL_ENDED'
export const SET_DATA_TO_CORE = 'SET_DATA_TO_CORE'
export const SET_DATA_TO_CORE_CO = 'SET_DATA_TO_CORE_CO'
export const SUBMIT_DATA_TO_CORE = 'SUBMIT_DATA_TO_CORE'
export const GET_HISTORY_CLIENT = 'GET_HISTORY_CLIENT'

// eKYC Setting
export const SET_LIST_PRODUCTS_KIND = 'SET_LIST_PRODUCTS_KIND'
export const SET_LIST_PRODUCTS_GROUP = 'SET_LIST_PRODUCTS_GROUP'
export const SET_LIST_PRODUCTS_CAMPAIGN_CODE = 'SET_LIST_PRODUCTS_CAMPAIGN_CODE'
export const SET_LIST_PRODUCTS_CATEGORY = 'SET_LIST_PRODUCTS_CATEGORY'
export const SET_LIST_PROVINCES = 'SET_LIST_PROVINCES'
export const SET_LIST_CITIES = 'SET_LIST_CITIES'
export const SET_LIST_DISTRICTS = 'SET_LIST_DISTRICTS'
export const SET_LIST_COMPANY = 'SET_LIST_COMPANY'
export const SET_LIST_APP_RESOURCE = 'SET_LIST_APP_RESOURCE'

// Noti Template
export const UPDATE_NOTI_TEMPLATE_SUCCESS = 'UPDATE_NOTI_TEMPLATE_SUCCESS'
export const SET_NOTI_TEMPLATES = 'SET_NOTI_TEMPLATES'
export const SET_IS_SHOW_EDIT_MODAL = 'SET_IS_SHOW_EDIT_MODAL'
export const SET_NOTI_TEMPLATE_EDIT_FORM = 'SET_NOTI_TEMPLATE_EDIT_FORM'
export const SET_NOTI_TEMPLATE_DEEP_LINK = 'SET_NOTI_TEMPLATE_DEEP_LINK'
export const SET_NOTI_TEMPLATE_DIALOG_ACTION = 'SET_NOTI_TEMPLATE_DIALOG_ACTION'

// export const FETCH_FORCE_CLOSE_REQUEST = 'FETCH_FORCE_CLOSE_REQUEST'
// export const FETCH_LINK_EXPORT_FORCE_CLOSE_DETAIL = 'FETCH_LINK_EXPORT_FORCE_CLOSE_DETAIL'
// export const FETCH_LINK_EXPORT_LOAN_ADDITIONAL_DETAIL = 'FETCH_LINK_EXPORT_LOAN_ADDITIONAL_DETAIL'
// export const FETCH_TENURE_DATA = 'FETCH_TENURE_DATA'
// export const CREATE_TENURE_DATA = 'CREATE_TENURE_DATA'
// export const CREATE_RATE_PER_YEAR_DATA = 'CREATE_RATE_PER_YEAR_DATA'
// export const LOAN_LIMIT_DETAIL = 'LOAN_LIMIT_DETAIL'
// export const SAVE_LOAN_LIMIT_DETAIL = 'SAVE_LOAN_LIMIT_DETAIL'
// export const LOAN_INCOME_MONTH_DETAIL = 'LOAN_INCOME_MONTH_DETAIL'
// export const SAVE_LOAN_INCOME_MONTH_DETAIL = 'SAVE_LOAN_INCOME_MONTH_DETAIL'
// export const UPDATE_LOAN_TOPUP_STATUS = 'UPDATE_LOAN_TOPUP_STATUS'
// export const UPDATE_LOAN_REQUEST_ADDITIONAL_STATUS = 'UPDATE_LOAN_REQUEST_ADDITIONAL_STATUS'
// export const NO_DATA_EXPORT_FORCE_CLOSE = 'NO_DATA_EXPORT_FORCE_CLOSE'
// export const NO_DATA_EXPORT_ADDITIONAL_LOAN = 'NO_DATA_EXPORT_ADDITIONAL_LOAN'

export const FETCH_CARD_MANAGEMENT = 'FETCH_CARD_MANAGEMENT'
export const UPDATE_CARD_MANAGEMENT = 'UPDATE_CARD_MANAGEMENT'
export const FETCH_LINK_EXPORT_CARD_REQUEST = 'FETCH_LINK_EXPORT_CARD_REQUEST'
export const NO_DATA_EXPORT_CARD_REQUEST = 'NO_DATA_EXPORT_CARD_REQUEST'
